name: tigo
description: "Tigo turns your journey into a story using a Gemini-powered live chatbot and expressive Rive animations."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  #Default
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Collection
  collection: ^1.18.0

  # Icons
  cupertino_icons: ^1.0.6

  # Localization
  intl: ^0.19.0
  timezone: ^0.9.4

  # Logger
  logger: ^2.4.0

  # GetX
  get: ^4.6.6

  # firebase
  firebase_core: ^3.13.0
  firebase_messaging: ^15.1.5
  firebase_auth: ^5.5.3
  firebase_vertexai: ^1.6.0

  # google cloud platform (gcp)
  google_sign_in: ^6.3.0
  google_maps_flutter: ^2.12.1
  google_generative_ai: ^0.4.7

  # geolocation
  geolocator: ^14.0.0
  geofence_foreground_service: ^1.1.5

  # permission
  permission_handler: ^12.0.0+1

  # youtube
  youtube_explode_dart: ^2.3.6
  youtube_player_iframe: ^4.0.4

  # STT & TTS
  flutter_tts: ^3.8.5
#  speech_to_text: ^7.0.0

  # socket
  socket_io_client: ^3.1.2
  web_socket_channel: ^3.0.3
  stomp_dart_client: ^2.1.3

  # rive
  rive: ^0.13.20

  # for LiveChatBot
  camera: ^0.11.1
  flutter_sound: ^9.28.0
  image: ^4.5.4
  audioplayers: ^6.4.0
  path_provider: ^2.1.5

  #
  # UI
  device_preview: ^1.2.0
  soft_edge_blur: ^0.1.3
  cupertino_will_pop_scope: ^1.2.1 #pop scope (스와이프 백 제스쳐 지원)
  flutter_svg: ^2.0.10+1 # SVG 아이콘
  flutter_easyloading: ^3.0.5 # 로딩 UI 처리 관련
  fluttertoast: ^8.2.2 # 토스트
  flutter_chat_bubble: ^2.0.2 # 말풍선
  font_awesome_flutter: ^10.5.0 # 아이콘
  smooth_page_indicator: ^1.1.0 # pageview 인디케이터
  flutter_animate: ^4.2.0+1 # 간편 애니메이션 메소드 지원
  flutter_layout_grid: ^2.0.7
  lottie: ^3.2.0
  smooth_sheets: ^0.10.2
  expandable_page_view: ^1.0.17
  measure_size_builder: ^1.0.3
  bounce_tapper: ^1.1.4

  # Shimmer
  shimmer: ^3.0.0

  # Cached Network Image
  cached_network_image: ^3.4.1
  cached_memory_image: ^1.5.0

  # Extended Nested Scroll View
  extended_nested_scroll_view: ^6.2.1

  # Dotenv
  flutter_dotenv: ^5.1.0

  # Storage
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.2

  # Environment Encrypted
  envied: ^0.5.4+1

  # Percent Indicator
  carousel_slider: ^4.2.1
  syncfusion_flutter_charts: ^24.1.45

  # Custom Time Chart
  path_drawing: ^1.0.1
  touchable: ^1.0.2
  linked_scroll_controller: ^0.2.0

  # ft_chart
  fl_chart: ^0.66.0
  cloud_firestore: ^5.6.7
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.4.6
  dotenv: ^4.2.0

dev_dependencies:
  # Default
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Localization
  intl_translation: ^0.20.0

  # app icon
  flutter_launcher_icons: ^0.13.1

  # Environment Encrypted
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.11

  analyzer: "6.4.1"

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/
    - assets/prompts/
    - assets/config/.env

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
