///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  // images
  static const String askTigoBtnImage = 'assets/images/ask_tigo_btn_image.png';
  static const String askTigoImage = 'assets/images/ask_tigo_image.png';
  static const String cheonggyecheonImage =
      'assets/images/cheonggyecheon_image.png';
  static const String flagFranceImage = 'assets/images/flag_france_image.png';
  static const String folkMuseumImage = 'assets/images/folk_museum_image.png';
  static const String googleLogoImage = 'assets/images/google_logo_image.png';
  static const String gradientBackgroundImage =
      'assets/images/gradient_background_image.png';
  static const String homeGradientBackgroundImage =
      'assets/images/home_gradient_background_image.png';
  static const String parisBackgroundImage =
      'assets/images/paris_background_image.png';
  static const String romeImage = 'assets/images/rome_image.png';
  static const String chatTigoImage = 'assets/images/chat_tigo_image.png';
  static const String sanFranciscoImage =
      'assets/images/san_francisco_image.png';
  static const String tigoCharacterImage =
      'assets/images/tigo_character_image.png';
  static const String thumbnailTokyoImage =
      'assets/images/thumbnail_tokyo_image.png';
  static const String thumbnailParisImage =
      'assets/images/thumbnail_paris_image.png';
  static const String thumbnailRomeImage =
      'assets/images/thumbnail_rome_image.png';
  static const String splashImage = 'assets/images/splash_image.png';
  static const String distanceLineImage =
      'assets/images/distance_line_image.png';

  // icons
  static const String distanceIcon = 'assets/icons/distance_icon.svg';
  static const String homeIcon = 'assets/icons/home_icon.svg';
  static const String profileIcon = 'assets/icons/profile_icon.svg';
  static const String webcamIcon = 'assets/icons/webcam_icon.svg';
  static const String homePureIcon = 'assets/icons/home_pure_icon.svg';
  static const String clockIcon = 'assets/icons/clock_icon.svg';
  static const String globeIcon = 'assets/icons/globe_icon.svg';
  static const String pathIcon = 'assets/icons/path_icon.svg';
  static const String thumbDownIcon = 'assets/icons/thumb_down_icon.svg';
  static const String thumbUpIcon = 'assets/icons/thumb_up_icon.svg';
  static const String iconsGoogleLogo = 'assets/icons/google_logo.svg';
  static const String appIcon = 'assets/icons/app_icon.svg';

  // riv
  static const String walkRive = 'assets/animations/walk.riv';
  static const String pingpongRive = 'assets/animations/pingpong.riv';
}
